USE [FinalProject]
GO
/****** Object:  Table [dbo].[RawData]    Script Date: 25-Apr-23 6:39:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RawData](
	[SNO] [int] NULL,
	[MRD No#] [int] NULL,
	[D#O#A] [datetime] NULL,
	[D#O#D] [datetime] NULL,
	[AGE] [int] NULL,
	[GENDER] [nvarchar](255) NULL,
	[RURAL] [nvarchar](255) NULL,
	[TYPE OF ADMISSION-EMERGENCY/OPD] [nvarchar](255) NULL,
	[month year] [datetime] NULL,
	[DURATION OF STAY] [int] NULL,
	[duration of intensive unit stay] [int] NULL,
	[OUTCOME] [nvarchar](255) NULL,
	[SMOKING ] [bit] NULL,
	[ALCOHOL] [bit] NULL,
	[DM] [bit] NULL,
	[HTN] [bit] NULL,
	[CAD] [bit] NULL,
	[PRIOR CMP] [bit] NULL,
	[CKD] [bit] NULL,
	[HB] [decimal](7,2) NULL,
	[TLC] [decimal](7,2) NULL,
	[PLATELETS] [decimal](7,2) NULL,
	[GLUCOSE] [decimal](7,2) NULL,
	[UREA] [decimal](7,2) NULL,
	[CREATININE] [decimal](7,2) NULL,
	[BNP] [int] NULL,
	[RAISED CARDIAC ENZYMES] [bit] NULL,
	[EF] [int] NULL,
	[SEVERE ANAEMIA] [bit] NULL,
	[ANAEMIA] [bit] NULL,
	[STABLE ANGINA] [bit] NULL,
	[ACS] [bit] NULL,
	[STEMI] [bit] NULL,
	[ATYPICAL CHEST PAIN] [bit] NULL,
	[HEART FAILURE] [bit] NULL,
	[HFREF] [bit] NULL,
	[HFNEF] [bit] NULL,
	[VALVULAR] [bit] NULL,
	[CHB] [bit] NULL,
	[SSS] [bit] NULL,
	[AKI] [bit] NULL,
	[CVA INFRACT] [bit] NULL,
	[CVA BLEED] [bit] NULL,
	[AF] [bit] NULL,
	[VT] [bit] NULL,
	[PSVT] [bit] NULL,
	[CONGENITAL] [bit] NULL,
	[UTI] [bit] NULL,
	[NEURO CARDIOGENIC SYNCOPE] [bit] NULL,
	[ORTHOSTATIC] [bit] NULL,
	[INFECTIVE ENDOCARDITIS] [bit] NULL,
	[DVT] [bit] NULL,
	[CARDIOGENIC SHOCK] [bit] NULL,
	[SHOCK] [bit] NULL,
	[PULMONARY EMBOLISM] [bit] NULL,
	[CHEST INFECTION] [bit] NULL
) ON [PRIMARY]
GO
